CREATE TABLE chef_data (
    chef_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    gender VARCHAR(50),
    c_address VARCHAR(255),
    city VARCHAR(255),
    nationality VARCHAR(100),       
    years_of_experience INT,                         
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (1, 'Aimee', 'Gatch', 'agatch0@dot.gov', 'Female', '0301 Hollow Ridge Hill', 'Khasht’arrak', 'Latin American Indian', 36, '2024-08-26 21:22:26');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (2, 'Margarete', 'Melton', 'mmelton1@go.com', 'Female', '64 Summer Ridge Terrace', 'Ivanec', 'Spaniard', 24, '2024-03-31 14:20:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (3, 'Edvard', 'Neno', 'eneno2@nyu.edu', 'Male', '3 Armistice Court', 'Xilin', 'Latin American Indian', 11, '2023-04-08 03:00:33');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (4, 'Alphonse', 'Arnopp', 'aarnopp3@ucoz.ru', 'Male', '7932 Sauthoff Street', 'Carvalho', 'Eskimo', 25, '2024-01-17 16:16:15');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (5, 'Cairistiona', 'Petrushka', 'cpetrushka4@oracle.com', 'Genderqueer', '74 Gerald Way', 'Bulbul', 'Chickasaw', 27, '2023-01-27 12:10:38');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (6, 'Kennith', 'Watchorn', 'kwatchorn5@blogger.com', 'Male', '91517 Corry Terrace', 'La Mesa', 'Venezuelan', 8, '2023-08-02 05:46:38');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (7, 'Carlen', 'Peddar', 'cpeddar6@dropbox.com', 'Female', '9 Florence Circle', 'Paris 12', 'Guamanian', 34, '2023-02-05 06:20:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (8, 'Tedie', 'Menendez', 'tmenendez7@vimeo.com', 'Male', '66997 Oriole Plaza', 'Madagali', 'Choctaw', 4, '2024-08-23 00:22:33');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (9, 'Oren', 'Braunes', 'obraunes8@adobe.com', 'Male', '37 Mandrake Place', '‘Ayn al Bayḑā', 'Comanche', 21, '2023-04-18 06:15:01');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (10, 'Simonne', 'Durrell', 'sdurrell9@yale.edu', 'Female', '4 Meadow Ridge Alley', 'Tāndo Mittha Khān', 'Guamanian', 16, '2023-11-09 07:03:12');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (11, 'Dermot', 'Chittim', 'dchittima@fastcompany.com', 'Male', '8 School Road', 'Caramuca', 'Paiute', 26, '2023-06-26 08:58:04');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (12, 'Alden', 'Feige', 'afeigeb@omniture.com', 'Male', '55 Grover Road', 'Mönsterås', 'Spaniard', 40, '2023-08-11 23:57:02');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (13, 'Garfield', 'Timberlake', 'gtimberlakec@dailymail.co.uk', 'Male', '19 Clove Place', 'San Isidro', 'Native Hawaiian', 16, '2024-03-05 22:05:55');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (14, 'Jasun', 'Donnersberg', 'jdonnersbergd@nba.com', 'Male', '92383 Crowley Pass', 'Masindi', 'Choctaw', 40, '2024-03-23 02:27:06');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (15, 'Griffin', 'Roswarn', 'groswarne@fotki.com', 'Male', '29557 Stang Way', 'Uijeongbu-si', 'White', 30, '2024-09-23 17:18:25');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (16, 'Desi', 'Wrightem', 'dwrightemf@xinhuanet.com', 'Non-binary', '3 Scoville Pass', 'Mislak', 'Osage', 5, '2023-11-20 14:30:37');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (17, 'Rod', 'Windibank', 'rwindibankg@wufoo.com', 'Male', '36296 Moland Place', 'Vysoké Mýto', 'Kiowa', 32, '2024-10-13 12:56:35');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (18, 'Shanta', 'Warrier', 'swarrierh@loc.gov', 'Female', '49 2nd Terrace', 'Lyon', 'Indonesian', 0, '2023-02-24 12:17:26');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (19, 'Orbadiah', 'Anyene', 'oanyenei@si.edu', 'Male', '2833 Linden Way', 'Seattle', 'Chippewa', 39, '2024-06-22 14:55:17');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (20, 'Izak', 'Follet', 'ifolletj@usda.gov', 'Genderqueer', '9 Hoepker Center', 'Xiangying', 'Peruvian', 20, '2024-07-21 07:11:23');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (21, 'Thorndike', 'Beswell', 'tbeswellk@squidoo.com', 'Male', '63 Brown Crossing', 'Solor', 'Blackfeet', 39, '2024-03-01 13:24:09');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (22, 'Magdalene', 'Scrivner', 'mscrivnerl@barnesandnoble.com', 'Female', '96714 Washington Place', 'Xinglong', 'Central American', 9, '2024-07-15 12:51:40');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (23, 'Rhea', 'Kestell', 'rkestellm@mashable.com', 'Female', '38187 Lotheville Road', 'Madang', 'Spaniard', 7, '2024-09-01 03:09:52');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (24, 'Merilyn', 'Hacon', 'mhaconn@ocn.ne.jp', 'Female', '99 Ilene Place', 'Gombong', 'Cuban', 26, '2023-09-25 07:27:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (25, 'Ronald', 'Leyman', 'rleymano@cdbaby.com', 'Male', '91 Merry Lane', 'Morelos', 'Mexican', 28, '2023-11-23 18:32:19');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (26, 'Heath', 'Kahn', 'hkahnp@un.org', 'Female', '619 Valley Edge Drive', 'Rondonópolis', 'Pakistani', 12, '2024-04-12 19:55:04');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (27, 'Garvin', 'Hemstead', 'ghemsteadq@youtube.com', 'Genderfluid', '50 Shelley Point', 'Pataias', 'Indonesian', 39, '2022-12-30 22:17:06');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (28, 'Enrica', 'Collingridge', 'ecollingridger@about.com', 'Female', '5061 Declaration Park', 'Tanshan', 'Micronesian', 29, '2023-03-01 16:03:34');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (29, 'Walsh', 'Wisker', 'wwiskers@cdbaby.com', 'Male', '0 Darwin Crossing', 'Pabean', 'Kiowa', 21, '2024-10-27 17:52:00');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (30, 'Valera', 'Elston', 'velstont@twitpic.com', 'Female', '36251 Hollow Ridge Center', 'Hua Hin', 'Guatemalan', 29, '2023-04-05 18:11:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (31, 'Shirleen', 'Losemann', 'slosemannu@java.com', 'Genderqueer', '1 Talmadge Street', 'Maiorca', 'Choctaw', 24, '2024-09-22 00:30:11');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (32, 'Norman', 'Kinsey', 'nkinseyv@seesaa.net', 'Male', '10 Kennedy Pass', 'El Ángel', 'Laotian', 23, '2024-10-26 07:33:23');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (33, 'Marillin', 'Valti', 'mvaltiw@sogou.com', 'Female', '7549 Shopko Avenue', 'Tianxing', 'Delaware', 5, '2023-03-13 22:23:20');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (34, 'Rosaleen', 'Wagerfield', 'rwagerfieldx@mozilla.com', 'Female', '16 Hoepker Street', 'Tost', 'Malaysian', 17, '2022-12-09 22:13:19');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (35, 'Peria', 'Poundford', 'ppoundfordy@ustream.tv', 'Female', '421 Bashford Point', 'Żyrardów', 'Paraguayan', 35, '2024-03-30 18:03:21');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (36, 'Wolfy', 'Ludlamme', 'wludlammez@abc.net.au', 'Male', '794 Donald Street', 'Haveli', 'Ottawa', 4, '2024-10-08 07:03:38');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (37, 'Jimmy', 'Mainds', 'jmainds10@biblegateway.com', 'Male', '34 Surrey Crossing', 'Naikoten Dua', 'Vietnamese', 7, '2023-02-20 13:01:12');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (38, 'Cleopatra', 'Curnok', 'ccurnok11@tinypic.com', 'Female', '85413 Dixon Place', 'Panitan', 'Osage', 28, '2024-03-27 21:30:53');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (39, 'Elna', 'Leivers', 'eleivers12@theguardian.com', 'Female', '23278 Lotheville Pass', 'De la Paz', 'Alaska Native', 5, '2024-11-06 22:55:56');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (40, 'Chiarra', 'Charville', 'ccharville13@utexas.edu', 'Female', '845 Northport Parkway', 'Metz', 'Aleut', 34, '2024-05-23 10:32:50');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (41, 'Krishnah', 'Pringuer', 'kpringuer14@a8.net', 'Male', '81081 Dexter Plaza', 'San Carlos', 'Salvadoran', 17, '2023-04-03 13:39:26');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (42, 'Priscella', 'Fawke', 'pfawke15@xing.com', 'Polygender', '39 8th Court', 'Buchanan', 'Dominican (Dominican Republic)', 29, '2023-08-21 10:59:10');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (43, 'Gregorio', 'Constantinou', 'gconstantinou16@mashable.com', 'Male', '00 Merrick Alley', 'Chengnan', 'Chilean', 36, '2024-04-29 02:30:46');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (44, 'Brandice', 'Heffer', 'bheffer17@hud.gov', 'Female', '3 Orin Avenue', 'Marhanets’', 'Korean', 3, '2024-02-10 11:53:28');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (45, 'Aristotle', 'Bernardinelli', 'abernardinelli18@drupal.org', 'Male', '951 Jana Trail', 'Basar', 'Crow', 39, '2024-04-11 16:23:53');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (46, 'Rois', 'Vasilik', 'rvasilik19@webeden.co.uk', 'Female', '3 Lawn Lane', 'Pechersk', 'Osage', 8, '2023-09-14 04:30:43');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (47, 'Janice', 'Kringe', 'jkringe1a@godaddy.com', 'Female', '8658 Darwin Way', 'Miraflores', 'Guatemalan', 4, '2023-11-01 12:11:44');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (48, 'Avigdor', 'Forster', 'aforster1b@huffingtonpost.com', 'Male', '2 Cordelia Street', 'Yelan’-Kolenovskiy', 'South American', 21, '2024-09-24 21:23:42');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (49, 'Regan', 'Potzold', 'rpotzold1c@addthis.com', 'Female', '6981 Hallows Point', 'Sucre', 'Ecuadorian', 33, '2023-04-01 10:23:42');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (50, 'Munroe', 'Frunks', 'mfrunks1d@privacy.gov.au', 'Male', '3 Chive Plaza', 'Rossosh’', 'Chinese', 9, '2023-10-23 21:01:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (51, 'Rayshell', 'Milhench', 'rmilhench1e@cnn.com', 'Female', '2 Eastlawn Avenue', 'Nesovice', 'Paraguayan', 2, '2024-11-08 07:42:10');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (52, 'Ede', 'Lepoidevin', 'elepoidevin1f@yolasite.com', 'Agender', '6 Longview Road', 'Ribeiro', 'Melanesian', 23, '2023-06-14 17:47:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (53, 'Steve', 'Kenlin', 'skenlin1g@uiuc.edu', 'Male', '49 Bultman Trail', 'Potlot', 'Creek', 35, '2023-07-21 07:25:50');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (54, 'Alair', 'Holston', 'aholston1h@cloudflare.com', 'Male', '91471 Superior Plaza', 'Bayang', 'Pakistani', 34, '2023-03-20 07:17:39');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (55, 'Anderea', 'Fitzsimmons', 'afitzsimmons1i@ning.com', 'Genderqueer', '87775 Lindbergh Pass', 'Strawberry Hills', 'Malaysian', 10, '2024-05-08 20:32:48');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (56, 'Hendrik', 'Starzaker', 'hstarzaker1j@examiner.com', 'Male', '9 Hanson Crossing', 'Catamayo', 'Thai', 8, '2024-01-13 19:08:47');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (57, 'Judon', 'Clinnick', 'jclinnick1k@senate.gov', 'Male', '54 Northwestern Center', 'Tisno', 'Chinese', 29, '2024-09-21 09:27:54');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (58, 'Verla', 'Rodder', 'vrodder1l@slate.com', 'Female', '338 North Point', 'Kotabaru', 'Crow', 12, '2023-12-31 15:00:10');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (59, 'Becka', 'Sattin', 'bsattin1m@eepurl.com', 'Female', '34 2nd Way', 'Konārak', 'Cherokee', 16, '2023-07-05 09:17:30');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (60, 'Otto', 'Klesse', 'oklesse1n@wikipedia.org', 'Male', '0 Spaight Center', 'Kota Bharu', 'Pueblo', 2, '2024-01-21 19:14:25');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (61, 'Charin', 'Dudding', 'cdudding1o@t-online.de', 'Female', '29248 Esker Court', 'Villa Santa Rita', 'Pueblo', 18, '2023-11-29 21:30:33');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (62, 'Erminia', 'Ivanonko', 'eivanonko1p@tinypic.com', 'Female', '7 Schlimgen Court', 'Xinyan', 'Bangladeshi', 26, '2024-01-05 15:28:48');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (63, 'Chloris', 'Madoc-Jones', 'cmadocjones1q@goo.gl', 'Polygender', '00528 Mallard Pass', 'Pittsburgh', 'Filipino', 6, '2023-11-23 17:47:53');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (64, 'Tess', 'Brain', 'tbrain1r@infoseek.co.jp', 'Female', '499 Lillian Point', 'Łękawica', 'Apache', 33, '2023-12-18 14:49:01');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (65, 'Barnett', 'Flacknell', 'bflacknell1s@nytimes.com', 'Male', '57 Fair Oaks Place', 'Borik', 'Aleut', 9, '2023-10-19 10:44:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (66, 'Hesther', 'Winkett', 'hwinkett1t@dot.gov', 'Female', '356 Fallview Trail', 'Houston', 'Malaysian', 14, '2024-07-20 16:22:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (67, 'Fionnula', 'Wissbey', 'fwissbey1u@scribd.com', 'Female', '358 Anhalt Road', 'Wapno', 'Micronesian', 23, '2023-12-17 17:48:49');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (68, 'Chester', 'Selwood', 'cselwood1v@hostgator.com', 'Male', '65 Monica Park', 'Citeureup', 'Bangladeshi', 14, '2023-11-19 12:45:10');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (69, 'Megen', 'Gilford', 'mgilford1w@dagondesign.com', 'Female', '8 Ridgeview Park', 'Puning', 'Navajo', 11, '2024-11-17 13:04:39');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (70, 'Pammie', 'Chettoe', 'pchettoe1x@vkontakte.ru', 'Female', '62003 Arkansas Trail', 'Darmasari', 'Hmong', 17, '2024-09-10 14:12:58');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (71, 'Danika', 'Marcam', 'dmarcam1y@dailymotion.com', 'Female', '4 Mayer Circle', 'Psebay', 'Peruvian', 7, '2023-08-18 10:06:47');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (72, 'Rose', 'Splevin', 'rsplevin1z@reddit.com', 'Female', '02 Westend Circle', 'Richards Bay', 'Crow', 40, '2024-10-19 07:00:22');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (73, 'Scot', 'Trattles', 'strattles20@cornell.edu', 'Male', '52147 Melby Parkway', 'Lingyuan', 'Blackfeet', 11, '2024-01-27 06:11:57');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (74, 'Joellyn', 'Szymanek', 'jszymanek21@sun.com', 'Female', '415 Scofield Drive', 'Ishikawa', 'Honduran', 19, '2023-08-23 12:10:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (75, 'Levi', 'Heatly', 'lheatly22@sogou.com', 'Male', '0 Mccormick Drive', 'Mafa', 'Eskimo', 34, '2024-02-04 10:48:00');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (76, 'Ado', 'Bew', 'abew23@live.com', 'Male', '141 Crownhardt Point', 'Corona', 'Black or African American', 20, '2023-12-03 06:49:16');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (77, 'Holmes', 'Mozzi', 'hmozzi24@apache.org', 'Male', '47395 Anthes Drive', 'Kurkino', 'Osage', 1, '2023-12-02 19:48:33');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (78, 'Mayne', 'De Ortega', 'mdeortega25@oracle.com', 'Male', '81190 Clove Street', 'Cidadap', 'Paraguayan', 18, '2023-01-09 02:32:38');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (79, 'Lilias', 'Hannen', 'lhannen26@qq.com', 'Female', '0 Bluejay Terrace', 'Marcos', 'Pima', 17, '2023-06-23 21:44:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (80, 'Waiter', 'Skeete', 'wskeete27@php.net', 'Male', '29184 Arrowood Pass', 'Bom Jesus da Lapa', 'Cheyenne', 31, '2023-03-15 07:48:35');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (81, 'Renaldo', 'Wingham', 'rwingham28@tinyurl.com', 'Male', '1 Stone Corner Way', 'Trollhättan', 'Crow', 0, '2022-12-03 12:11:38');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (82, 'Kassi', 'Revey', 'krevey29@nyu.edu', 'Female', '82231 Hintze Parkway', 'Hengqu', 'American Indian and Alaska Native (AIAN)', 21, '2024-02-12 06:14:05');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (83, 'Cecil', 'Duckers', 'cduckers2a@istockphoto.com', 'Female', '85 Hoffman Crossing', 'Tlumach', 'Alaskan Athabascan', 11, '2023-04-14 12:18:02');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (84, 'Cortie', 'Varley', 'cvarley2b@google.com.hk', 'Male', '98309 Drewry Plaza', 'Orivesi', 'Chippewa', 21, '2023-11-02 08:05:29');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (85, 'Ferdinanda', 'Ivermee', 'fivermee2c@ehow.com', 'Female', '6 Straubel Hill', 'Síkinos', 'Melanesian', 34, '2024-11-09 10:52:16');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (86, 'Brnaba', 'Buggy', 'bbuggy2d@sourceforge.net', 'Male', '03142 New Castle Street', 'Chirongui', 'Colombian', 21, '2023-07-12 17:24:51');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (87, 'Ralph', 'Necolds', 'rnecolds2e@gizmodo.com', 'Male', '10 Monterey Court', 'Longmen', 'Puget Sound Salish', 5, '2023-03-05 03:19:21');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (88, 'Heddi', 'Torritti', 'htorritti2f@photobucket.com', 'Female', '6549 Summerview Court', 'Ubay', 'Dominican (Dominican Republic)', 29, '2024-09-20 05:54:19');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (89, 'Kippie', 'Sarfas', 'ksarfas2g@google.cn', 'Female', '13 5th Road', 'Longlisuo', 'Pima', 11, '2024-07-07 22:17:40');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (90, 'Brook', 'Filipic', 'bfilipic2h@amazon.co.jp', 'Female', '84 Petterle Trail', 'Farah', 'Samoan', 8, '2022-12-16 18:11:32');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (91, 'Carleen', 'Rosenblad', 'crosenblad2i@cocolog-nifty.com', 'Female', '868 Talmadge Plaza', 'Singaraja', 'Pakistani', 16, '2024-05-07 13:08:58');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (92, 'Isabelita', 'Mundwell', 'imundwell2j@dmoz.org', 'Female', '1 Meadow Ridge Plaza', 'Liboran', 'Indonesian', 3, '2024-04-04 08:49:59');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (93, 'Karim', 'De la Harpe', 'kdelaharpe2k@webmd.com', 'Male', '1 Southridge Court', 'Walahir', 'Malaysian', 5, '2023-07-31 04:46:49');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (94, 'Carita', 'Forsbey', 'cforsbey2l@exblog.jp', 'Female', '8 Algoma Center', 'Shanlian', 'Asian', 4, '2023-01-25 01:07:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (95, 'Susie', 'Phillpotts', 'sphillpotts2m@soup.io', 'Female', '82084 Sullivan Drive', 'Vigo', 'Blackfeet', 24, '2023-08-15 06:32:42');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (96, 'Nicki', 'Drewe', 'ndrewe2n@list-manage.com', 'Female', '5 Almo Point', 'Veldhoven', 'Samoan', 11, '2023-09-20 18:37:33');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (97, 'Devan', 'Mehew', 'dmehew2o@ted.com', 'Female', '52301 Trailsway Terrace', 'Mandiana', 'Chinese', 10, '2024-06-18 13:29:18');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (98, 'Mohandis', 'Walcher', 'mwalcher2p@noaa.gov', 'Male', '3 Village Terrace', 'Järfälla', 'Aleut', 32, '2023-07-23 12:05:19');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (99, 'Ibby', 'Cranney', 'icranney2q@independent.co.uk', 'Female', '33762 Shasta Crossing', 'Changyi', 'Bolivian', 17, '2023-08-02 02:10:31');
insert into chef_data (chef_id, first_name, last_name, email, gender, C_address, city, nationality, years_of_experience, date_added) values (100, 'Hector', 'Rattry', 'hrattry2r@godaddy.com', 'Male', '71742 Schmedeman Park', '‘Irbīn', 'Chinese', 19, '2024-09-03 21:01:57');
